### ISSUE TITLE
field addItem

### ISSUE THREAD

**Issue by themano** [CryptoGenics/redemrp_weaponshop#4]
I started this resource after inventory but didnt work
I have this problem
![Névtelen](https://user-images.githubusercontent.com/71080639/102122051-3d79f380-3e45-11eb-976d-1e96bba2c6d1.png)

**Comment by icrescenti** [comment]
@themano Any solution yet?

**Comment by CryptoGenics** [comment]
Inventory 2.0 support just added, just setup accordingly.
